### ISSUE TITLE
Alfred Version Not Supported

### ISSUE THREAD

**Issue by monsterandy** [mr-pennyworth/AlfredSwift#1]
Hello, I received an error message from the AlfredExtraPane, but it seems that the issue is connected to this library.

"This workflow uses an Alfred feature only available in v4.3.0 and newer. The installed Alfred version is v0.0.0."

![image](https://github.com/mr-pennyworth/AlfredSwift/assets/19617700/ec58ac60-ac4a-4a6b-abd0-0126aa9475fb)

I am using an M2 Mac with macOS 14.3.1 (23D60), and the Alfred version is 5.1.4 [2195].

**Comment by mr-pennyworth** [comment]
Thanks @monsterandy for the report!
I have fixed it in f258d48. This bug went uncaught because on my machine, have both `Alfred 4.app` and the new `Alfred 5.app` 😅
